name: Manual Snyk Scan

on:
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  snyk-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Debug — show current directory
        run: pwd

      - name: Debug — list files
        run: ls -la

      - name: Snyk Open Source scan (SCA)
        run: snyk test --file=AdventOfCode-2024/AdventOfCode2024/AdventOfCode2024.sln

      - name: Snyk Code scan (SAST)
        run: snyk code test --no-cache
